# Configuration file
# key = value
quarkus:
  datasource:
  db-kind: postgresql
  reactive:
    url: postgresql://localhost:5432/travelhub
#quarkus.datasource.username=quarkus_test
#quarkus.datasource.password=quarkus_test
